# Generated by Django 6.0.6 on 2026-09-09 21:05

import django.db.models.deletion
import getpaid_core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                (
                    'amount_required',
                    models.DecimalField(
                        decimal_places=2,
                        help_text='Amount required to fulfill the payment; in selected currency, normal notation',
                        max_digits=20,
                        verbose_name='amount required',
                    ),
                ),
                (
                    'currency',
                    models.CharField(max_length=3, verbose_name='currency'),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('new', 'new'),
                            ('prepared', 'in progress'),
                            ('pre-auth', 'pre-authed'),
                            ('charge_started', 'charge process started'),
                            ('partially_paid', 'partially paid'),
                            ('paid', 'paid'),
                            ('failed', 'failed'),
                            ('refund_started', 'refund started'),
                            ('refunded', 'refunded'),
                            ('cancelled', 'cancelled'),
                        ],
                        db_index=True,
                        default=getpaid_core.enums.PaymentStatus['NEW'],
                        max_length=50,
                        verbose_name='status',
                    ),
                ),
                (
                    'backend',
                    models.CharField(
                        db_index=True, max_length=100, verbose_name='backend'
                    ),
                ),
                (
                    'created_on',
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name='created on',
                    ),
                ),
                (
                    'last_payment_on',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name='paid on',
                    ),
                ),
                (
                    'amount_locked',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Amount locked with this payment, ready to charge.',
                        max_digits=20,
                        verbose_name='amount locked',
                    ),
                ),
                (
                    'amount_paid',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text='Amount actually paid.',
                        max_digits=20,
                        verbose_name='amount paid',
                    ),
                ),
                (
                    'refunded_on',
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name='refunded on',
                    ),
                ),
                (
                    'amount_refunded',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name='amount refunded',
                    ),
                ),
                (
                    'external_id',
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name='external id',
                    ),
                ),
                (
                    'description',
                    models.CharField(
                        blank=True,
                        default='',
                        max_length=128,
                        verbose_name='description',
                    ),
                ),
                (
                    'fraud_status',
                    models.CharField(
                        choices=[
                            ('unknown', 'unknown'),
                            ('accepted', 'accepted'),
                            ('rejected', 'rejected'),
                            ('check', 'needs manual verification'),
                        ],
                        db_index=True,
                        default=getpaid_core.enums.FraudStatus['UNKNOWN'],
                        max_length=20,
                        verbose_name='fraud status',
                    ),
                ),
                (
                    'fraud_message',
                    models.TextField(blank=True, verbose_name='fraud message'),
                ),
                (
                    'provider_data',
                    models.JSONField(
                        blank=True, default=dict, verbose_name='provider data'
                    ),
                ),
                (
                    'id',
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                (
                    'order',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payments',
                        to='durable_test_app.order',
                        verbose_name='order',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_on'],
                'abstract': False,
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                'status',
                                getpaid_core.enums.PaymentStatus['FAILED'],
                            ),
                            _negated=True,
                        ),
                        fields=('order',),
                        name='getpaid_unique_non_failed_payment_per_order',
                    )
                ],
            },
        ),
    ]
