# Generated by Django 2.0.7 on 2018-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Lock, Stock and Two Smoking Barrels", max_length=100
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default="199.99", max_digits=8
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Waiting for payment"),
                            ("P", "Payment complete"),
                        ],
                        default="W",
                        max_length=1,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
