# Generated by Django 6.0.2 on 2026-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20200417_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompayment',
            name='amount_refunded',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name='amount refunded',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
    ]
