# Generated by Django 3.0.6 on 2020-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200608_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompayment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='description'),
        ),
    ]
