# Generated by Django 6.0.5 on 2026-07-04 13:30

import getpaid_core.enums
from django.db import migrations, models


def _blank_external_id_to_null(apps, schema_editor):
    CustomPayment = apps.get_model('orders', 'CustomPayment')
    CustomPayment.objects.filter(external_id='').update(external_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_custompayment_provider_data'),
    ]

    operations = [
        # Make the column nullable first, normalize '' -> NULL, then add
        # the unique constraint so pre-existing blank rows cannot collide.
        migrations.AlterField(
            model_name='custompayment',
            name='external_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                verbose_name='external id',
            ),
        ),
        migrations.RunPython(
            _blank_external_id_to_null,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='custompayment',
            name='external_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
                verbose_name='external id',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='custompayment',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('status', getpaid_core.enums.PaymentStatus['FAILED']),
                    _negated=True,
                ),
                fields=('order',),
                name='getpaid_unique_non_failed_payment_per_order',
            ),
        ),
    ]
