# Generated by Django 3.0.6 on 2020-07-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200717_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custompayment',
            options={'ordering': ['-created_on'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='custompayment',
            name='message',
            field=models.TextField(blank=True, max_length=256, verbose_name='wiadomość do klienta'),
        ),
    ]
