# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Lock, Stock and Two Smoking Barrels', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=b'199.99', max_digits=8)),
                ('currency', models.CharField(default=b'EUR', max_length=3)),
                ('status', models.CharField(blank=True, choices=[(b'W', b'Waiting for payment'), (b'P', b'Payment complete')], default=b'W', max_length=1)),
            ],
        ),
    ]
