# Generated by Django 6.0.6 on 2026-09-09 21:41

import getpaid_core.enums
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paywall', '0004_remove_fsm_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymententry',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('new', 'new'),
                    ('prepared', 'in progress'),
                    ('pre-auth', 'pre-authed'),
                    ('charge_started', 'charge process started'),
                    ('partially_paid', 'partially paid'),
                    ('paid', 'paid'),
                    ('failed', 'failed'),
                    ('refund_started', 'refund started'),
                    ('partially_refunded', 'partially refunded'),
                    ('refunded', 'refunded'),
                    ('cancelled', 'cancelled'),
                ],
                default=getpaid_core.enums.PaymentStatus['PREPARED'],
                max_length=50,
            ),
        ),
    ]
