# Generated by Django 3.0.6 on 2020-05-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0003_payment_redirect_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='external_refund_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='external refund id'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='refund description'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status_desc',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256, verbose_name='refund status description'),
        ),
    ]
