# Generated by Django 6.0.2 on 2026-03-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('getpaid', '0004_payment_provider_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_locked',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Amount locked with this payment, ready to charge.',
                max_digits=20,
                verbose_name='amount locked',
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_refunded',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=20,
                verbose_name='amount refunded',
            ),
        ),
    ]
