# Generated by Django 3.0.6 on 2020-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0005_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
