# Generated by Django 6.0.5 on 2026-05-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getpaid", "0005_alter_payment_amount_locked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                unique=True,
                verbose_name="external id",
            ),
        ),
    ]
