# Generated by Django 3.0.6 on 2020-06-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0006_payout_customer_name'),
        ('getpaid', '0006_auto_20200608_1221'),
    ]

    operations = [
    ]
