# Generated by Django 6.0.5 on 2026-07-04 13:30

from django.db import migrations, models


def _blank_external_id_to_null(apps, schema_editor):
    Payment = apps.get_model('getpaid', 'Payment')
    if Payment._meta.swapped:
        # Payment model swapped out; nothing to normalize here.
        return
    Payment.objects.filter(external_id='').update(external_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0007_unique_non_failed_payment_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
                verbose_name='external id',
            ),
        ),
        migrations.RunPython(
            _blank_external_id_to_null,
            migrations.RunPython.noop,
        ),
    ]
