# Generated by Django 3.0.6 on 2020-06-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0007_merge_20200608_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='description'),
        ),
    ]
