# Generated by Django 3.0.6 on 2020-06-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0008_auto_20200610_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='amount withdrawed'),
        ),
    ]
