# Generated by Django 6.0.6 on 2026-07-04 22:09

import getpaid_core.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getpaid', '0008_alter_payment_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(
                choices=[
                    ('new', 'new'),
                    ('prepared', 'in progress'),
                    ('pre-auth', 'pre-authed'),
                    ('charge_started', 'charge process started'),
                    ('partially_paid', 'partially paid'),
                    ('paid', 'paid'),
                    ('failed', 'failed'),
                    ('refund_started', 'refund started'),
                    ('refunded', 'refunded'),
                    ('cancelled', 'cancelled'),
                ],
                db_index=True,
                default=getpaid_core.enums.PaymentStatus['NEW'],
                max_length=50,
                verbose_name='status',
            ),
        ),
    ]
