# Generated by Django 6.0.6 on 2026-09-09 20:47

import django.db.models.deletion
import swapper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('getpaid', '0009_alter_payment_status'),
        swapper.dependency('getpaid', 'Payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurablePaymentState',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('facts', models.JSONField()),
                ('reconciliation_required', models.BooleanField(db_index=True)),
                (
                    'payment',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='durable_state',
                        to=swapper.get_model_name('getpaid', 'Payment'),
                    ),
                ),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DurableOperation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('operation_id', models.TextField()),
                ('record', models.JSONField()),
                ('unresolved', models.BooleanField(db_index=True)),
                (
                    'payment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='getpaid.durablepaymentstate',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('payment', 'operation_id'),
                        name='getpaid_durable_operation_identity',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='DurableReplay',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('backend', models.TextField()),
                ('event_identity', models.TextField()),
                ('content_digest', models.CharField(max_length=64)),
                (
                    'payment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='getpaid.durablepaymentstate',
                    ),
                ),
            ],
            options={
                'constraints': [
                    models.UniqueConstraint(
                        fields=('payment', 'backend', 'event_identity'),
                        name='getpaid_durable_replay_identity',
                    )
                ],
            },
        ),
    ]
