# Generated by Django 6.0.6 on 2026-09-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("getpaid", "0011_alter_payment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="DurableRecordedMoneyEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command_id", models.TextField()),
                ("record", models.JSONField()),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="getpaid.durablepaymentstate",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payment", "command_id"),
                        name="getpaid_recorded_money_identity",
                    )
                ],
            },
        ),
    ]
